// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'class_list_store.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MyCard _$MyCardFromJson(Map<String, dynamic> json) => MyCard(
      id: json['id'] as String?,
      storename: json['storename'] as String?,
      province: json['province'] as String?,
      namepro: json['namepro'] as String?,
      picpro: json['picpro'] as String?,
      timepost: json['timepost'] as String?,
      timeopen: json['timeopen'] as String?,
      favorite: json['favorite'] as bool?,
      dianamepro: json['dianamepro'] as String?,
      diapicpro: json['diapicpro'] as String?,
      diatime: json['diatime'] as String?,
      note: json['note'] as String?,
      picStore: json['picStore'] as List<dynamic>?,
      foodname: json['foodname'] as List<dynamic>?,
      picfood: json['picfood'] as List<dynamic>?,
      price: json['price'] as List<dynamic>?,
      dayopen: json['dayopen'] as String?,
      dianote: json['dianote'] as List<dynamic>?,
      region: json['region'] as String?,
      dayoff: json['dayoff'] as String?,
      tel: json['tel'] as List<dynamic>?,
      storetype: json['storetype'] as String?,
      flav: json['flav'] as String?,
      diafav: json['diafav'] as int?,
      diapicdes: json['diapicdes'] as List<dynamic>?,
      email: json['email'] as String?,
      fooddes: json['fooddes'] as List<dynamic>?,
      lat: (json['lat'] as num?)?.toDouble(),
      lng: (json['lng'] as num?)?.toDouble(),
      user: json['user'] as List<dynamic>?,
      url: json['url'] as List<dynamic>?,
      rating: (json['rating'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$MyCardToJson(MyCard instance) => <String, dynamic>{
      'id': instance.id,
      'storename': instance.storename,
      'storetype': instance.storetype,
      'namepro': instance.namepro,
      'picpro': instance.picpro,
      'timepost': instance.timepost,
      'timeopen': instance.timeopen,
      'dayopen': instance.dayopen,
      'dianamepro': instance.dianamepro,
      'diapicpro': instance.diapicpro,
      'diatime': instance.diatime,
      'note': instance.note,
      'flav': instance.flav,
      'region': instance.region,
      'dayoff': instance.dayoff,
      'province': instance.province,
      'email': instance.email,
      'foodname': instance.foodname,
      'fooddes': instance.fooddes,
      'picStore': instance.picStore,
      'picfood': instance.picfood,
      'dianote': instance.dianote,
      'price': instance.price,
      'diapicdes': instance.diapicdes,
      'tel': instance.tel,
      'user': instance.user,
      'url': instance.url,
      'diafav': instance.diafav,
      'rating': instance.rating,
      'lat': instance.lat,
      'lng': instance.lng,
      'favorite': instance.favorite,
    };

Store _$StoreFromJson(Map<String, dynamic> json) => Store(
      id: json['id'] as String?,
      storename: json['storename'] as String?,
      province: json['province'] as String?,
      namepro: json['namepro'] as String?,
      picpro: json['picpro'] as String?,
      timepost: json['timepost'] as String?,
      timeopen: json['timeopen'] as String?,
      favorite: json['favorite'] as bool?,
      dianamepro: json['dianamepro'] as String?,
      diapicpro: json['diapicpro'] as String?,
      diatime: json['diatime'] as String?,
      note: json['note'] as String?,
      picStore: json['picStore'] as List<dynamic>?,
      foodname: json['foodname'] as List<dynamic>?,
      picfood: json['picfood'] as List<dynamic>?,
      price: json['price'] as List<dynamic>?,
      dayopen: json['dayopen'] as String?,
      dianote: json['dianote'] as List<dynamic>?,
      region: json['region'] as String?,
      dayoff: json['dayoff'] as String?,
      tel: json['tel'] as List<dynamic>?,
      storetype: json['storetype'] as String?,
      flav: json['flav'] as String?,
      diafav: json['diafav'] as int?,
      diapicdes: json['diapicdes'] as List<dynamic>?,
      email: json['email'] as String?,
      fooddes: json['fooddes'] as List<dynamic>?,
      lat: (json['lat'] as num?)?.toDouble(),
      lng: (json['lng'] as num?)?.toDouble(),
      user: json['user'] as List<dynamic>?,
      url: json['url'] as List<dynamic>?,
      rating: (json['rating'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$StoreToJson(Store instance) => <String, dynamic>{
      'id': instance.id,
      'storename': instance.storename,
      'storetype': instance.storetype,
      'namepro': instance.namepro,
      'picpro': instance.picpro,
      'timepost': instance.timepost,
      'timeopen': instance.timeopen,
      'dayopen': instance.dayopen,
      'dianamepro': instance.dianamepro,
      'diapicpro': instance.diapicpro,
      'diatime': instance.diatime,
      'note': instance.note,
      'flav': instance.flav,
      'region': instance.region,
      'dayoff': instance.dayoff,
      'province': instance.province,
      'email': instance.email,
      'foodname': instance.foodname,
      'fooddes': instance.fooddes,
      'picStore': instance.picStore,
      'picfood': instance.picfood,
      'dianote': instance.dianote,
      'price': instance.price,
      'diapicdes': instance.diapicdes,
      'tel': instance.tel,
      'user': instance.user,
      'url': instance.url,
      'diafav': instance.diafav,
      'rating': instance.rating,
      'lat': instance.lat,
      'lng': instance.lng,
      'favorite': instance.favorite,
    };
