// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'class_list_travel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MyCard _$MyCardFromJson(Map<String, dynamic> json) => MyCard(
      id: json['id'] as String?,
      locationname: json['locationname'] as String?,
      province: json['province'] as String?,
      namepro: json['namepro'] as String?,
      picpro: json['picpro'] as String?,
      timepost: json['timepost'] as String?,
      timeopen: json['timeopen'] as String?,
      favorite: json['favorite'] as bool?,
      dianamepro: json['dianamepro'] as String?,
      diapicpro: json['diapicpro'] as String?,
      diatime: json['diatime'] as String?,
      note: json['note'] as String?,
      pictravel: json['pictravel'] as List<dynamic>?,
      goodtime: json['goodtime'] as String?,
      dayopen: json['dayopen'] as String?,
      dianote: json['dianote'] as List<dynamic>?,
      region: json['region'] as String?,
      dayoff: json['dayoff'] as String?,
      tel: json['tel'] as List<dynamic>?,
      locationtype: json['locationtype'] as String?,
      flav: json['flav'] as String?,
      diafav: json['diafav'] as int?,
      activity: json['activity'] as List<dynamic>?,
      email: json['email'] as String?,
      adultfee: json['adultfee'] as String?,
      lat: (json['lat'] as num?)?.toDouble(),
      lng: (json['lng'] as num?)?.toDouble(),
      childfee: json['childfee'] as String?,
      foreignerfees: json['foreignerfees'] as String?,
      rating: (json['rating'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$MyCardToJson(MyCard instance) => <String, dynamic>{
      'id': instance.id,
      'locationname': instance.locationname,
      'locationtype': instance.locationtype,
      'namepro': instance.namepro,
      'picpro': instance.picpro,
      'timepost': instance.timepost,
      'timeopen': instance.timeopen,
      'dayopen': instance.dayopen,
      'dianamepro': instance.dianamepro,
      'diapicpro': instance.diapicpro,
      'diatime': instance.diatime,
      'note': instance.note,
      'flav': instance.flav,
      'region': instance.region,
      'dayoff': instance.dayoff,
      'goodtime': instance.goodtime,
      'childfee': instance.childfee,
      'adultfee': instance.adultfee,
      'foreignerfees': instance.foreignerfees,
      'province': instance.province,
      'email': instance.email,
      'pictravel': instance.pictravel,
      'dianote': instance.dianote,
      'activity': instance.activity,
      'tel': instance.tel,
      'diafav': instance.diafav,
      'rating': instance.rating,
      'lat': instance.lat,
      'lng': instance.lng,
      'favorite': instance.favorite,
    };

Travel _$TravelFromJson(Map<String, dynamic> json) => Travel(
      id: json['id'] as String?,
      locationname: json['locationname'] as String?,
      province: json['province'] as String?,
      namepro: json['namepro'] as String?,
      picpro: json['picpro'] as String?,
      timepost: json['timepost'] as String?,
      timeopen: json['timeopen'] as String?,
      favorite: json['favorite'] as bool?,
      dianamepro: json['dianamepro'] as String?,
      diapicpro: json['diapicpro'] as String?,
      diatime: json['diatime'] as String?,
      note: json['note'] as String?,
      pictravel: json['pictravel'] as List<dynamic>?,
      goodtime: json['goodtime'] as String?,
      dayopen: json['dayopen'] as String?,
      dianote: json['dianote'] as List<dynamic>?,
      region: json['region'] as String?,
      dayoff: json['dayoff'] as String?,
      tel: json['tel'] as List<dynamic>?,
      locationtype: json['locationtype'] as String?,
      flav: json['flav'] as String?,
      diafav: json['diafav'] as int?,
      activity: json['activity'] as List<dynamic>?,
      email: json['email'] as String?,
      adultfee: json['adultfee'] as String?,
      lat: (json['lat'] as num?)?.toDouble(),
      lng: (json['lng'] as num?)?.toDouble(),
      childfee: json['childfee'] as String?,
      foreignerfees: json['foreignerfees'] as String?,
      rating: (json['rating'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$TravelToJson(Travel instance) => <String, dynamic>{
      'id': instance.id,
      'locationname': instance.locationname,
      'locationtype': instance.locationtype,
      'namepro': instance.namepro,
      'picpro': instance.picpro,
      'timepost': instance.timepost,
      'timeopen': instance.timeopen,
      'dayopen': instance.dayopen,
      'dianamepro': instance.dianamepro,
      'diapicpro': instance.diapicpro,
      'diatime': instance.diatime,
      'note': instance.note,
      'flav': instance.flav,
      'region': instance.region,
      'dayoff': instance.dayoff,
      'goodtime': instance.goodtime,
      'childfee': instance.childfee,
      'adultfee': instance.adultfee,
      'foreignerfees': instance.foreignerfees,
      'province': instance.province,
      'email': instance.email,
      'pictravel': instance.pictravel,
      'dianote': instance.dianote,
      'activity': instance.activity,
      'tel': instance.tel,
      'diafav': instance.diafav,
      'rating': instance.rating,
      'lat': instance.lat,
      'lng': instance.lng,
      'favorite': instance.favorite,
    };
